### ISSUE TITLE
Rtv dont show message

### ISSUE THREAD

**Issue by altulter** [Silenci0/UMC#14]
i instaled the umc and the rtv dont show messages, also the admin menu doesnt do nothing,

**Comment by altulter** [comment]
fresh dedicated server, only the umc plugin, and the umc shows installed but doesn't work just do nothing (csgo)

**Comment by Silenci0** [comment]
Could you show your umc_mapcycle.txt file and the umc configuration files?

**Comment by altulter** [comment]
"umc_mapcycle"
{
    "Surf-KILL" 
	{
	"maps_invote"           "1" 
	"group_weight"          "3"

	"surf_tuvieja_pb"{}
	"surf_aero_violence"{}
	"surf_candyskate_pb"{}
	"surf_colos2"{}
	"surf_combat_28"{}
	"surf_dust2_2018_fix"{}
	"surf_fillory"{}
	"surf_greatriver_csgofix"{}
	"surf_green_impact_csgo_v1"{}
	"surf_japan_z3"{}
	"surf_lagoon_v1"{}
	"surf_old_sand"{}
	"surf_ski_2"{}
	"surf_ski_2_GO"{}
	"surf_ski_2_night_csgo"{}
	"surf_ski_2_source_fixed"{}
	"surf_ski_2_tsr_v1-7-2"{}
	"surf_skydreams_v8"{}
	"surf_smoothcv3"{}	
	"surf_solarium_v2"{}	
}

    "Multigames" 
	{
	"maps_invote"           "1"
	"group_weight"          "2"


	"mg_100traps_v4_2"{}
	"mg_adev"{}
	"mg_awp_submarine_v4csgo"{}
	"mg_canalrun_course_v09"{}
	"mg_circle_course"{}
	"mg_cyber_course_v5"{}
	"mg_lego_multigames_v8"{}
	"mg_mahnig_course_v4"{}
	"mg_minecraft_adventure_final_fix"{}
	"mg_minecraft_course_jb_n1"{}
	"mg_minecraft_multigames_v4"{}
	"mg_mirai_nikki"{}
	"mg_saw_2"{}
	"mg_saw_3_v1"{}
	"mg_saw_iv_csgo"{}
	"mg_sonic_islands_v4"{}	
	

}

    "Aim/FY" 
	{
	"maps_invote"           "1"
	"group_weight"          "1"


	"aim_allgun"{}
	"aim_deagle7k"{}
	"aim_allpistols_2017_a"{}
	"aim_dev_allpistols_v1"{}
	"aim_redline"{}
	"aim_redline_2019"{}
	"am_aztec2"{}
	"am_aztec2015"{}
	"am_minecraft_shift"{}
	"am_minecraft_shift"{}
	"am_nuke2"{}
	"Simpsons"{}
	"fy_pool_day"{}
	"fy_asteroide"{}
	"fy_iceworld"{}
	"2000_classic"{}
	"2000_csgo"{}
}



  "Battle Royale" 
	{
	"maps_invote"           "1"

	"dr_canyon_beta"{}
	"dm_royale_remix"{}
}


  "AWP" 
	{
	"maps_invote"           "1"

	"35hp_2_2015"{}
	"35hp_colors"{}
	"awp_india_csgo"{}
	"awp_lego_9"{}
	"awp_lego_2015"{}
	"awp_lego_2016"{}
	"awp_lego_fix_v6"{}
	"awp_minecraft"{}
}	
	
 "Casual" 
	{
	"maps_invote"           "1"

	"de_nuke_classic"{}
	"de_dust2_old"{}
	"de_dust2_night"{}
	"de_dust2_classic"{}
	"de_dust2_winter"{}
	"de_aztec_proper"{}
	"de_aztec_mini_go"{}
	"de_aztec_classic"{}
	

}
	
}

**Comment by altulter** [comment]
And all the cfg are as default

**Comment by Silenci0** [comment]
Hello,

Sorry for the late response on this, but while working on a UMC update, I have been able to look into part of this issue, but only for TF2. The messages that RTV outputs, by default in the configurations, are all located in the chat, so any RTV information, including which maps won, will show up there. 

As for the admin menu, I was able to get it to work as well without any issue. I was able to change maps, call votes, etc. from the UMC admin menu. However, the default configuration files list the admin flag "z" as the default flag for the UMC admin menu, so one potential issue could be that your admin permissions were not set with the correct flag, so it would not come up or show/do anything, which might explain what you were seeing. 

Because I've been testing in TF2 and not in CS:GO, I can say the functionality is working for TF2, but CS:GO might be a different matter. I will be doing a few tests on CS:GO in the future to determine if this bug is actually specifically related to just that game. For now, I will be labeling this issue as a potential CS:GO bug and will respond back when I have more information regarding this particular issue.

**Comment by Silenci0** [comment]
I have tested the latest update (3.7.0) of UMC for CS:GO and did not run into either issue with the admin menu and the RTV messages, so if it was broken for CS:GO, it should be fixed in the latest UMC update. If you are still using UMC and having the same issue, please try out the updated UMC version. If it still does not work, then it might be a configuration issue or something else is interfering.

I will be closing this issue now. If new issues come up, feel free to let me know.
