### ISSUE TITLE
Too much maps in map cycle leads to lag.

### ISSUE THREAD

**Issue by Uronic** [Silenci0/UMC#17]
I don't really know if this can be fixed but whenever I have too much maps on umc it leads to lag. The lag happens when someone goes through the map groups in nominate and when rtv/mapend voting occurs. 

Here is my ginormous mapcycle
[umc_mapcycle.txt](https://github.com/Silenci0/UMC/files/3741115/umc_mapcycle.txt)

**Comment by Silenci0** [comment]
Hello Uronic,

This is a known issue with the plugin and, unfortunately, it is not something that can be fixed, at least not for UMC as it is now. The problem, in the simplest technical terms, is that all of the map choices have to be parsed and loaded into several arrays in memory that need to hold onto the various nominations, choices, and data as well going through the UMC mapcycle file itself when called upon on top of doing all of the other stuff the plugin needs to do. 

Because of the complexity of this plugin, it is highly unlikely that this will ever get fixed unless it is completely rewritten and even then, it will most likely have similar issues with very large mapcycle files. So the only other option is to look at the mapcycle file and reduce the amount of maps or the complexity of the file itself to help reduce/mitigate the lag issues. Most users with mapcycle files with 200-300 maps start to see similar lag symptoms when calling on votes/nominations, especially if they have lots of map groups, have the same maps in different map groups, and if they are using lots of map options, including the map display name option, in their UMC mapcycle file. 

 _**In your specific case,**_ the reason it is lagging is due to having a lot of maps (about 743 maps to be exact) in your UMC mapcycle file. The only real solution is to reduce the number of map options available in your mapcycle file. In this case, I have a few suggestions that might help you to eliminate these lag symptoms:

- Remove older versions of maps from the mapcycle file itself in favor of the latest versions. I see a number of map names that are similar to one another, so I assume they are older entries. If you no longer play those versions or those versions no longer exist, it might be wise to remove them from the mapcycle file.
- Remove maps that your community does not like to play. For the amount of maps you have, it might be a difficult task to figure out, especially when players have so many opinions on what the "good" maps are for the gamemodes in question, but it would help to alleviate some of the lag symptoms by removing underplayed or unpopular maps. Your largest map group is KZ, followed by Bunnyhop, Minigames, and Combatsurf in that order, so a lot of your map eliminations will probably come from those groups first, so the parts of the community that play those gamemodes might be able to tell you which maps are the better maps to play in general.
- Remove map groups that never get played/used. Much like the second suggestion, this one would rely knowing which is the most popular gamemodes on your server and which is the least popular. Eliminating the least popular gamemode would remove the maps associated to it from the mapcycle, reducing the lag when calling on votes.

Alternatively, if you'd rather not remove any of these maps or mapcycles, another possible, but more drastic), solution to consider would be to move your largest (and I presume the most popular) gamemodes to its own server dedicated to that gamemode. While a very roundabout way to eliminate the lag symptoms surrounding this plugin, and forgive me if it comes across as too bold as it is not my intention to make any assumptions about your gaming community or server, it might be better overall to consider this option if the above suggestions are not to your liking and if some of those gamemodes on your server are more popular among your players. Obviously, this would be more expensive to do and it does carry its own risks, but if you happen to have a large enough community to warrant some of the gamemodes to be moved to their own server, it might prove beneficial to both your server and to those players who commonly play on the server for that specific gamemode. 

I am sorry that I cannot fix this for you via the plugin itself, but I hope that the above options are somewhat helpful to you. 

Thank you,

Silence
Silence

**Comment by Silenci0** [comment]
I will be closing this issue. Please feel free to respond back to this if need be. I hope your lag issues have been fixed.
