### ISSUE TITLE
Cannot nominate until the next map for vote based on frags remaining

### ISSUE THREAD

**Issue by eisgottin** [Silenci0/UMC#19]
Hello silenci0.

There is an unpleasant situation for Nominations, when the round is is limited  by mp_fraglimit.
If the top players did not get to the desired number of frags and 

left the server. 
Other players do not want to finish the card. They write "nominate", but the card cannot be nominated, because Voting has already taken place. UMC print to chat "Cannot nominate until the next map".

The only thing players can do is write rtv. But the card for rtv cannot be nominated if voting for the next card has already taken place.

[umc-endvote.zip](https://github.com/Silenci0/UMC/files/4055531/umc-endvote.zip)

**Comment by Silenci0** [comment]
If I'm understanding this correctly, the issue seems to be that a map vote occurs when players near the value stored in mp_fraglimit and the vote is successful(?), but the top player that is closest to the frag limit leaves, meaning the other players have to reach that frag limit in order to change the map as they cannot RTV or nominate a new map, correct? If that is the case, then I can see how that can be frustrating to deal with. 

However, as far as the voting mechanic is concerned, this is unfortunately not a bug, but an intended mechanic of the plugin. Once a vote is called, whether it is through an RTV/Nominate vote or an end of round (or close to end of round) vote, another vote cannot be called again after a vote succeeds. The plugin was designed this way to make sure that people wouldn't attempt to start another vote to override the previous vote or to abuse the plugin once a vote had already been called. 

With that said, there are a couple of ways that this can be resolved with the options available:

- Disable the map endvote, setup randomcycle so that the nextmap will be chosen at random, and set RTV to change instantly when called upon. With this option, players will only vote when a nominate/RTV is called and if they don't vote and win the round, the next map will just be automatically chosen. This would most likely prevent the issue you are facing.
- Have the endvote set to instantly change upon a successful vote during the last round. Depending on your setup, this might not be desirable, but it will ensure that no one has to sit on the same map after a vote when the top scoring players leave.

Most of the solutions to this problem would involve either instant map changes or only allowing users to RTV to determine the next map that they want. Alternatively, it might be a good idea to have an admin switch the maps when such a thing occurs, but that is assuming an active admin is on/playing when it occurs, which isn't always possible.

**Comment by eisgottin** [comment]
Thank you for your response and recommendations!
