### ISSUE TITLE
Add ConVar "prefix"

### ISSUE THREAD

**Issue by baferpro** [Silenci0/UMC#4]
Well, so that you can change [UMC] on something else

**Comment by Silenci0** [comment]
Hello Bafer,

You'll have to forgive me, but I'm not quite sure what you mean with prefix. Would you happen to mean an actual convar for a game named "prefix" or a plugin variable that allows you to set convar prefixes for games? The only prefix I recall is the umc-prefixexclude module, but if you mean something else, could you provide me more specific details about what you are referring to with this issue/request?

**Comment by baferpro** [comment]
Example:
```g_sPrefix = CreateConVar("umc_prefix", "\x03[UMC]\x01", "Prefix");```

```
char Prefix[128];
GetConVarString(g_sPrefix, Prefix, sizeof(Prefix));
PrintToChatAll(
                    "%s %t (%t)",
                   Prefix,
                    "Vote Failed",
                    "Vote Win Percentage",
                        percentage,
                        total_votes
                );
```

**Comment by Silenci0** [comment]
Hello,

I am very sorry for the late response to this feature request, but after reviewing it and looking into its feasibility for UMC, I have decided not to implement this feature. 

While it would be nice to change the tags, the unfortunate truth is that multiple plugins would require either referencing one plugin's prefix cvar or using their own prefix cvar in each module that has [UMC] tags in it. In all cases, it would mean adding additional work between/in the plugins themselves in order to accommodate this and, at present, I do not believe it would be worth the trade off performance-wise to do this. While the trade off in performance would be small, users that already experience issues with this plugin as a result of large, complicated maplists would end up running into further performance issues, which is why I have decided against this feature for UMC. If this were a more streamlined plugin (or an entirely new plugin), I would have gladly added it as I actually like the idea.

I will, however, be removing the color codes from the [UMC] tags in the message replies in favor of a more generic looking message in a future UMC update. This is just in case the game itself does not support color codes correctly (or at all) or if the color codes clash with other aspects of the game and the chat window.

Anyway, thank you for the feature request and, again, sorry for the very late response in regards to its status. I will be closing this issue.
