### ISSUE TITLE
How to setup voting and next map with workshop

### ISSUE THREAD

**Issue by abhishekdeshkar** [Silenci0/UMC#7]
Hello from India,

In my Bhop server, I have workshop maps. Now the issue is that default map change does show those maps during voting but it doesnt change the map. Even ```sm_map``` command doesnt work. 

While using ```sm_map <workshopmap_name>``` it shows in the console that map is changing to <XXXX> map but it doesn't actually change. 

I always have to manually change map using either ```host_workshop_map``` command or ```changelevel``` command.

Can I accomplish this task with UMC ? 

Thank you.!

**Comment by Silenci0** [comment]
Hello,

I believe it may work with workshop maps as it does make calls to changelevel via the Sourcemod API, but I have never tried it personally as I would have users download maps rather than utilize the workshop, so I don't know if it is actually working or not. 

It might help to know what game you are referring to, but in general, the plugin works for a number of games like CS:GO and TF2 so it will most likely work. Give it a try and find out if you are willing. If it doesn't, let me know.

Thanks,

Silence
