### ISSUE TITLE
How to stop nomination menu from autoclosing

### ISSUE THREAD

**Issue by fatt1** [Silenci0/UMC#8]
Hey! 

How can i stop the nomination menu closing after 20 (ish) seconds? I got like 350 maps on the server, so its insanely hard to go through them within that 20 seconds. Tried to look for solution in .sp files, but couldnt find it anywhere.
Also: Any tips on how to reduce the "lag spike" that occurs when vote is triggered and it fetches maps from big mapcycle?

Thanks upfront!

**Comment by Silenci0** [comment]
Hello,

As far as the nomination menu closing after 20 seconds, I don't think there is a cvar that controls that in the nominations module of UMC. I know endvotes and the rtv modules do have a time duration cvar, but I don't believe those will affect nomination menu duration. I'll probably have to add this in a future update since I don't think it was considered when the plugin was first created since most usually found their maps within 20 seconds.

As far as the lag spike, there are a couple of things you could try if you haven't done so:

- Do not use the "Display" option for map names if you have a lot of maps. This is one of the primary causes of the lag spike/crashing issue that is associated with the plugin. Its fine for smaller map cycle lists, but not for large ones.
- Remove duplicate map entries from various map groups. The more entries you have, the more work needs to be done to list them all on the server side. Removing or reducing the amount of duplicate entries will help alleviate some of the issues.
- Consolidate maps into fewer group categories. If you have several categories for maps, especially with duplicate map entries, it might be wise to see what groups you could combine together to create smaller lists.
- Remove old map versions that are no longer necessary from the map cycle file. I doubt this is an optimal option for you since you have so many maps, but if you've done all of the above, you may need to look into doing this just to reduce the size/complexity of the map cycle list. 

Aside from that, there isn't much else that can be done. Large map lists tend to cause the plugin to work pretty hard since it has to parse a lot of information. 

Silence

**Comment by div132** [comment]
Is there anyway to change the nomination menu closing setting in the .sp file and recompile?

**Comment by Silenci0** [comment]
Unfortunately no, at least not for changing the menu's duration. I believe it is using the default menu duration, so the plugin would need to do something similar to the endvotes and rtv plugins when it comes to duration, which would need to be added to the nominations plugin.

**Comment by Silenci0** [comment]
The latest updated for UMC (3.7.0) includes a new cvar in the nominations plugin called sm_umc_nominate_duration which acts like other duration cvars and is used to set the duration of the nominations menu itself. Its current default is 20 seconds, but you can increase the time limit to something higher and the menu should no longer close unless the time limit has been reached. This was tested in TF2 and CS:GO. 

Thank you for the report and let me know if you run into any more problems by opening a new ticket. Closing issue.
