### ISSUE TITLE
Few questions.

### ISSUE THREAD

**Issue by abhishekdeshkar** [Silenci0/UMC#9]
Hi,

I have few questions.

1. Is it compulsory to create a map list with group ? Can't I just use default mapcycle.txt for end round voting or RTV ?
2. I'm changing map on every 25 minutes and I have defined timelimit in server.cfg + I have unlimited round time. So does it waits for round end or it works based on remaining time ?
3. If I don't define map group and I want to add only list of maps then how do I do it ?

Also I keep getting this: 

```
L 03/01/2019 - 08:35:19: [umc-endvote.smx] Starting an end of map vote.

L 03/01/2019 - 08:35:19: [umc-core.smx] Not enough groups available for group vote, performing map vote with only group available.

L 03/01/2019 - 08:35:19: [umc-core.smx] Initiating Vote Type: Map

L 03/01/2019 - 08:35:25: [umc-core.smx] WARNING: Map "All Maps" does not exist on the server. (Group: "umc_rotation")

L 03/01/2019 - 08:35:25: [umc-core.smx] Setting nextmap to: 

L 03/01/2019 - 08:35:25: [umc-endvote.smx] End of map vote disabled.

L 03/01/2019 - 08:35:25: [umc-core.smx] MAPVOTE: Players voted for map group '2' and the map '' was randomly selected.
```

### Settigs I have changed in umc-endvote.cfg

```
// Controls end of map vote type:
//  0 - Maps,
//  1 - Groups,
//  2 - Tiered Vote (vote for a group, then vote for a map from the group).
// -
// Default: "0"
// Minimum: "0.000000"
// Maximum: "2.000000"
sm_umc_endvote_type "1.000000"

// Specifies when to start the vote based on time remaining in minutes.
// -
// Default: "6"
// Minimum: "2.000000"
sm_umc_endvote_starttime "1.000000"

// Specifies when to start the vote based on rounds remaining. Use 0 on TF2 to start vote during bonus round time
// -
// Default: "2"
// Minimum: "0.000000"
sm_umc_endvote_startrounds "0.000000"

// When to change the map after a successful vote:
//  0 - Instant,
//  1 - Round End,
//  2 - Map End
// -
// Default: "2"
// Minumum: "0.000000"
// Maximum: "2.000000"
sm_umc_endvote_changetime "2"

```
### umc_mapcycle.txt

```
"umc_mapcycle"
{
    "All Maps"
    {
        "maps_invote"    "3"

        "surf_utopia_v3" {}
        "surf_rookie" {}
        "surf_colours" {}
        "surf_rebel_scaz_njv" {}
        "surf_kitsune" {}
        "surf_colum_up" {}
        "surf_kitsune2_GO" {}
        "surf_beginner" {}
        "surf_calycate_csgo" {}
        "surf_mesa" {}
        "surf_classics" {}
        "surf_rebel_scaz_csgo" {}
        "surf_reprise" {}
        "surf_classics2" {}
        "surf_mesa_revo_go" {}
        "surf_amplitude_encore" {}
        "surf_life_of_duck" {}
        "surf_lux" {}
        "surf_lessons" {}
        "surf_aweles_d" {}
    }
}
```

Thanks a lot.

**Comment by Silenci0** [comment]
Answers to your questions:

1. To use UMC, you do need to create a map list with a group in the umc_mapcycle.txt as the plugin is looking for the format displayed in that file. Simply using mapcycle.txt wouldn't work if you are using UMC. You can use the same umc_mapcycle.txt file for rtv, endvote, everything. 
2. Assuming this game is CS:S or CS:GO, it should pick up on the value of the time limit cvar (which I am assuming is mp_timelimit) and based on the settings of sm_umc_endvote_starttime which will activate near the last minute of the round (based on your settings). 
3. You have to define a map group. You don't need to create multiple map groups, you can create just one and put all the maps within it. You just need to specify that your endvote settings, particular sm_umc_endvote_type, is set appropriately. In this case, sm_umc_endvote_type  should be set to 0 since you only have one map group.

There errors you are getting are due to the setting sm_umc_endvote_type to 1, which means you are voting on Map Groups before voting on maps. However, you only have 1 map group, which is why its causing issues. You should set the sm_umc_endvote_type to 0 instead to only vote on maps.

**Comment by abhishekdeshkar** [comment]
Thanks a lot.

However, what happens sometimes is at the end while changing map. It gets stuck. Map doesn't change.

```
CHANGELEVEL: Looking for next level in mapgroup '675035012'

Looking for next map in mapgroup '675035012'...

CHANGELEVEL: Choosing map 'workshop/675035012/surf_rookie' (previous was workshop/675013183/surf_calycate_csgo)

Msg from 183.87.117.91:27005: CCLCMsg_VoiceData rejected by msg bind (602 bytes)

CHANGELEVEL: Looking for next level in mapgroup '675035012'

Looking for next map in mapgroup '675035012'...

CHANGELEVEL: Choosing map 'workshop/675035012/surf_rookie' (previous was workshop/675013183/surf_calycate_csgo)

CHANGELEVEL: Looking for next level in mapgroup '675035012'

Looking for next map in mapgroup '675035012'...

CHANGELEVEL: Choosing map 'workshop/675035012/surf_rookie' (previous was workshop/675013183/surf_calycate_csgo)

CHANGE LEVEL: workshop/675035012/surf_rookie

L 03/01/2019 - 17:40:24: [SM] Changed map to "surf_aweles_d"

Dropped âªFlashu21K from server: Disconnect
```

As u can see it is calling map change but it doesnt change the map. it get stuck. 

```
L 03/01/2019 - 17:40:24: [SM] Changed map to "surf_aweles_d"
```

Any idea why ? This happens everytime  after 2-3  map changes. It works for 2-3 times then this happens.

You can connect to my surf server and check. IP is:  surf.ecsgaming.xyz

**Comment by Silenci0** [comment]
It looks like it is trying to find the map but it is unable to do so. Are all of these maps workshop maps and does this happen with all workshop maps or just a few of them on your list? I'm wondering if it just happens randomly or if there are specific maps that cause this problem.

**Comment by abhishekdeshkar** [comment]
But why would it look for this ``` Looking for next level in mapgroup '675035012' ``` when vote map is different ?

And why default map rotation is interfering in UMC? This should be handled by the UMC right ?

Btw if I restart server and put map using ```sm_map surf_aweles_d``` then it works. Then why it doesn't work with voting ?

**Comment by abhishekdeshkar** [comment]
Is there any cvar which enables random map change when no players on the server ? And when there are players, it will ask for votes.

**Comment by Silenci0** [comment]
There isn't a cvar in UMC that changes the server's map when empty. The game itself might have one, but not UMC. Assuming this is CS:GO, it is likely that it does have that cvar.

UMC itself looks to the umc_mapcycle.txt file for all of the maps that can be used. It does not look at the default map cycle/list files. If you have other map plugins enabled on the server alongside UMC, it might cause some of the issues such as the incorrect map being voted for. However, judging from the errors, it does not seem like it can find the correct map file, so there may be a bug with UMC (as stated in a previous question, I did not test workshop map functionality in UMC) or the formatting of the workshop map names are not correct for UMC as some others have asked in the original UMC thread about getting workshop maps to work in UMC. Depending on the game and OS used, the naming convention may need changed:

- CS:GO Windows requires Workshop maps to be in **workshop\[map id]** format.
- CS:GO Linux and TF2 all platforms require Workshop maps to be in **workshop/[map id]** format.

That is what I gathered from the original thread, so that may work here as well since the plugin is forked from the original thread's code.

**Comment by abhishekdeshkar** [comment]
Hi,

1. I have removed all default map management plugins like ```nextmap``` , ```mapchooser``` and ``rockthevote```.

2. Now I have kept maps with ```workshop/<id>``` let us see what happens.

```
"umc_rotation"
{
    "All Maps"
    {
        "maps_invote"    "4"

        "workshop/156054906/surf_utopia_v3" {}
        "workshop/675035012/surf_rookie" {}
        "workshop/259296700/surf_rebel_scaz_njv" {}
        "workshop/335802541/surf_kitsune" {}
        "workshop/543075184/surf_colum_up" {}
        "workshop/585589796/surf_kitsune2_GO" {}
        "workshop/607186931/surf_beginner" {}
        "workshop/675013183/surf_calycate_csgo" {}
        "workshop/675036474/surf_mesa" {}
        "workshop/676569663/surf_classics" {}
        "workshop/691186578/surf_rebel_scaz_csgo" {}
        "workshop/704807244/surf_reprise" {}
        "workshop/721085861/surf_classics2" {}
        "workshop/738984943/surf_mesa_revo_go" {}
        "workshop/1110512077/surf_amplitude_encore" {}
        "workshop/1193969466/surf_life_of_duck" {}
        "workshop/1193970046/surf_lux" {}
        "workshop/1429194400/surf_aweles_dsurf_aweles_d" {}
    }
}
```

3. I have strong feeling that even if I have disabled default map management plugins, they are still inferring in map change. As you can see it here and what is ```Going to intermission...``` ?

```
Going to intermission...

CHANGELEVEL: Looking for next level in mapgroup '675035012'

Looking for next map in mapgroup '675035012'...

CHANGELEVEL: Choosing map 'workshop/675035012/surf_rookie' (previous was workshop/675013183/surf_calycate_csgo)

Msg from 183.87.117.91:27005: CCLCMsg_VoiceData rejected by msg bind (602 bytes)

CHANGELEVEL: Looking for next level in mapgroup '675035012'

Looking for next map in mapgroup '675035012'...

CHANGELEVEL: Choosing map 'workshop/675035012/surf_rookie' (previous was workshop/675013183/surf_calycate_csgo)

CHANGELEVEL: Looking for next level in mapgroup '675035012'

Looking for next map in mapgroup '675035012'...

```

4. I got this cvar ```print_mapgroup_sv``` from alliedmodder which prints current available maps. In my case it is just printing one. I think it is linked to previous one where it says looking for next map in group and it has only one. BUT again the question is why it is looking for it when I have disabled all the default plugins. 

```
Map group: 675035012
     workshop/675035012/surf_rookie
```

**Comment by abhishekdeshkar** [comment]
@Silenci0  Any clue bro ?

**Comment by abhishekdeshkar** [comment]
Thank you @Silenci0 for helping me out. So I gave up on this issue. Wasted lot of time already. Thanks for your help though. Closing this issue. :)

**Comment by Silenci0** [comment]
Alright, thank you for letting me know. It seems that this is a bug with the plugin in terms of workshop map support so I will, when I have time, sit down and fix this issue as it is clearly missing from the plugin. Again, thank you for letting me know.
